name = "dishpage"
account_id = "d8ee18029fb3e06794971d45b9c4a67d"
main = "worker.ts"
compatibility_date = "2025-11-30"
compatibility_flags = ["nodejs_compat"]
assets = { binding = "ASSETS", directory = ".svelte-kit/cloudflare" }

[triggers]
# Cron format is UTC.
crons = ["0 * * * *"]

[observability]
enabled = true
head_sampling_rate = 1

[[d1_databases]]
binding = "DB"
database_name = "dishpage-database"
database_id = "7d89d33d-c90c-4e5b-806a-dd7e14ca0bd5"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "dishpage-bucket"

[[kv_namespaces]]
binding = "kv"
id = "b03debc71f6542a3aba848145d391cfa"
